spring:
  main:
    allow-circular-references: true
  data:
    cassandra:
      keyspace-name: main
      username: ${userName}
      password: ${password}
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
datastax.astra:
  secure-connect-bundle: secure-connect.zip

datadump.location:
  author: /home/ivan/Downloads/test-authors.txt
  works: /home/ivan/Downloads/test-works.txt
astra.db:
  id: 7738c04f-bb3d-44a8-a212-a0bf9b0d8e1a
  region: us-east1
  keyspace: main
  application.token: AstraCS:dXZhSGFkYnYaMyLdqKiSpxto:3e03bf12277c710e213c083a1f4f0c2e2eaa45ec0cdaf5f4da73128f12f410a7
